{% set name = "PsiTurk" %}
{% set version = "2.3.0" %}
{% set bundle = "tar.gz" %}
{% set hash_type = "sha256" %}
{% set hash = "c42fb3c5e86dc41cb97f97888384bb6ebef73ad117bdf22a7d98d0cf458b6871" %}
{% set build = 0 %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ bundle }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ bundle }}
  {{ hash_type }}: {{ hash }}

build:
  skip: True  # [py3k]
  noarch: python
  
  entry_points:
    - psiturk-shell = psiturk.psiturk_shell:run
    - psiturk = psiturk.command_line:process
    - psiturk-server = psiturk.command_line:process
    - psiturk-setup-example = psiturk.command_line:process
    - psiturk-install = psiturk.command_line:process

  number: {{ build }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    # All of these requirements are pinned in
    #  https://github.com/NYUCCL/psiTurk/blob/master/requirements.txt
    - python
    - argparse ==1.2.1  # [py<27]
    - flask ==0.12.1
    - sqlalchemy ==0.8.3
    - boto ==2.15.0
    - docopt ==0.6.2
    - requests ==2.5.0
    - psutil >=1.2.1
    - werkzeug ==0.12.1
    - gnureadline ==6.3.3  # [osx]
    # The below pinned requirements are unavailable for conda-forge
    # I've switched them to available requirements
    # The build seems succcessful
    - gunicorn ==19.6.0  # Pinned is 14.4.5
    - cmd2 ==0.6.8  # Pinned is 0.6.7
    - sh ==1.11  # Pinned is 1.09
    - fake-factory ==0.5.8  # Pinned is 0.3.2
    - fuzzywuzzy ==0.11.0  # Pinned is 0.2
    - gitpython ==2.0.8  # Pinned is 0.1.7
    - setproctitle ==1.1.10  # Pinned is 1.1.8
    - ua-parser ==0.7.1  # Pinned is 0.3.6
    - user-agents ==1.0.1  # Pinned is 0.2.0
    
test:
  imports:
    - psiturk
    - psiturk.amt_services
    - psiturk.command_line
    - psiturk.counter
    - psiturk.experiment_errors
    - psiturk.experiment_server_controller
    - psiturk.psiturk_config
    - psiturk.psiturk_org_services
    # - psiturk.db - requires a local config.txt file.
    # - psiturk.experiment - requires a local config.txt file.
    # - psiturk.experiment_server - requires a local config.txt file.
    # - psiturk.models - requires a local config.txt file.

  commands:
    - psiturk-shell --help
    - psiturk --help
    - psiturk-server --help
    - psiturk-setup-example --help
    - psiturk-install --help

about:
  home: https://psiturk.org/
  license_file: LICENSE
  license: MIT
  license_family: MIT
  summary: 'An open platform for science on Amazon Mechanical Turk'
  dev_url: https://github.com/NYUCCL/psiTurk
  doc_url: https://psiturk.org/docs/

extra:
  recipe-maintainers:
    - pmlandwehr
