{%set name = "PsiTurk" %}
{%set version = "2.1.6" %}
{%set compress_type = "tar.gz" %}
{%set hash_type = "sha256" %}
{%set hash_val = "3fea9276310cd0cd31ead13a027735dba4762cda6a7af05aa180390da541d930" %}
{%set build_num = "3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.{{ compress_type }}
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.{{ compress_type }}
  {{ hash_type }}: {{ hash_val }}

build:
  skip: True  # [win or py3k]
  entry_points:
    - psiturk-shell = psiturk.psiturk_shell:run
    - psiturk = psiturk.command_line:process
    - psiturk-server = psiturk.command_line:process
    - psiturk-setup-example = psiturk.command_line:process
    - psiturk-install = psiturk.command_line:process

  number: {{ build_num }}
  script: python setup.py install --single-version-externally-managed --record=record.txt

requirements:
  build:
    - python
    - setuptools

  run:
    # All of these requirements are pinned in
    #  https://github.com/NYUCCL/psiTurk/blob/master/requirements.txt
    - python
    - argparse ==1.2.1  # [py<27]
    - flask ==0.10.1
    - sqlalchemy ==0.8.3
    - gunicorn ==19.6.0
    - boto ==2.15.0
    - docopt ==0.6.2
    - requests ==2.2.1
    - psutil >=1.2.1
    - werkzeug ==0.10.4
    - readline ==6.3.3  # [osx]
    # The below pinned requirements are unavailable for conda-forge
    # I've switched them to available requirements
    # The build seems succcessful
    - cmd2 ==0.6.8  # Pinned is 0.6.7
    - sh ==1.11  # Pinned is 1.09
    - fake-factory ==0.5.8  # Pinned is 0.3.2
    - fuzzywuzzy ==0.11.0  # Pinned is 0.2
    - gitpython ==2.0.8  # Pinned is 0.1.7
    - setproctitle ==1.1.10  # Pinned is 1.1.8
    - ua-parser ==0.7.1  # Pinned is 0.3.6
    - user-agents ==1.0.1  # Pinned is 0.2.0

test:
  imports:
    - psiturk
    - psiturk.amt_services
    - psiturk.command_line
    - psiturk.counter
    - psiturk.experiment_errors
    - psiturk.experiment_server_controller
    - psiturk.psiturk_config
    - psiturk.psiturk_org_services
    # - psiturk.db - requires a local config.txt file.
    # - psiturk.experiment - requires a local config.txt file.
    # - psiturk.experiment_server - requires a local config.txt file.
    # - psiturk.models - requires a local config.txt file.

  commands:
    - psiturk-shell --help
    - psiturk --help
    - psiturk-server --help
    - psiturk-setup-example --help
    - psiturk-install --help

about:
  home: http://github.com/NYUCCL/psiturk
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: 'An open platform for science on Amazon Mechanical Turk'

extra:
  recipe-maintainers:
    - pmlandwehr
