# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode6.4

env:
  matrix:
    
    - CONDA_PY=27
  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "ZlktWiyr8eCcOyzzfwDMYOVWZW40uSw0Dvk4ua4l/8rEaMLlsq1pWF7djh+5K86pxzGRmFviBR8nuAl1LMJOtXvhsPRo24oHRfkkpGsULFuuyo+IB6Xkxejm+54lDTwIu9OTDZ4KlvW0+o/ZwKSbqNY91czuKsjpBZWEpM8ECglZkVljBnbGN/ULxzwBlfDkSXo8TXeRtRrrlYaSqKbRb4IlDwPY0JX2J02j0VEvPFnj0Iwxxop5N2BzFInrj8SAG9jbW90x5o7zxghu8GXVsVFN9WyYzyTt0//QnPm2M/aMtrlGuTU6s3v5/XTMu04DCINpx8xmG6O1zs3xNvcZaM9IiGjEyGkCW41NxRWpy+Jtjwvu6NLt2HQ3Gn7aEU0FfKm+5UHS+UiXGQB47eC05amDKPxf2FBH7Ok+vRpoiE/N/Eq3x5Q64u1JJf5cSZxT0dtN/ONHWXWpSMURNtekjo6YGOEQDqDVt//Tcw0bIwvvgNviId+x2qU3dmKoJe0T0msNaXOWTr82p99+fkkG/jVn6e7keBD5lZcOyrx/qhkTto5jjmvNrcEulp6A4MyHCKX0P93LKHxM0+63yaFTq1EebPPoj/tiKvTP+//GAhZqJQr9BO55BlzknCXQ//DrOiIFP2Dv7t7+zc3tjTX7z/VkZWEYrtr7bqtAyUM8XXI="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-build-setup-feedstock/master/recipe/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root
      conda config --remove channels defaults
      conda config --add channels defaults
      conda config --add channels conda-forge
      conda config --set show_channel_urls true
      conda install --yes --quiet conda-forge-build-setup
      source run_conda_forge_build_setup

script:
  - conda build ./recipe

  - upload_or_check_non_existence ./recipe conda-forge --channel=main
