travis:
  secure:
    BINSTAR_TOKEN: ZlktWiyr8eCcOyzzfwDMYOVWZW40uSw0Dvk4ua4l/8rEaMLlsq1pWF7djh+5K86pxzGRmFviBR8nuAl1LMJOtXvhsPRo24oHRfkkpGsULFuuyo+IB6Xkxejm+54lDTwIu9OTDZ4KlvW0+o/ZwKSbqNY91czuKsjpBZWEpM8ECglZkVljBnbGN/ULxzwBlfDkSXo8TXeRtRrrlYaSqKbRb4IlDwPY0JX2J02j0VEvPFnj0Iwxxop5N2BzFInrj8SAG9jbW90x5o7zxghu8GXVsVFN9WyYzyTt0//QnPm2M/aMtrlGuTU6s3v5/XTMu04DCINpx8xmG6O1zs3xNvcZaM9IiGjEyGkCW41NxRWpy+Jtjwvu6NLt2HQ3Gn7aEU0FfKm+5UHS+UiXGQB47eC05amDKPxf2FBH7Ok+vRpoiE/N/Eq3x5Q64u1JJf5cSZxT0dtN/ONHWXWpSMURNtekjo6YGOEQDqDVt//Tcw0bIwvvgNviId+x2qU3dmKoJe0T0msNaXOWTr82p99+fkkG/jVn6e7keBD5lZcOyrx/qhkTto5jjmvNrcEulp6A4MyHCKX0P93LKHxM0+63yaFTq1EebPPoj/tiKvTP+//GAhZqJQr9BO55BlzknCXQ//DrOiIFP2Dv7t7+zc3tjTX7z/VkZWEYrtr7bqtAyUM8XXI=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
