travis:
  secure:
    BINSTAR_TOKEN: Uw2EpJH7XDatr4EYlt1qptLYrKV7UEBukHaV+VE/IWjisxOJdBA/MAg8hdgIPmr+3XpyteEb+LEBpQ0wi+XmBGDfFi57n2EQK0wxi0KTdAidwIRV4rtWYvlsqnVzv39XIZJSbu1qQBUvYDB3RtqKBRaDFJPJBRUwynlNBVZvoY+4FzShrmF+HpbhVOPXDZjNgv1xMX/J4mh9Klko+kqWk9lzhTiG9TgB72UdbZOv+NerYccPESRdeX7PlQoeISMihRXcHi8FyC1QypIhkGi/ug0DxpjqWO96I/cOW5esnOfYNolv8Mr0SsDL/8J+4TsnmU2aNKxnl/kUWFYxmOsPsPZ2WnzaCg6sRauyxto/17CCGnuiqkpqyxk2xJfelA6XnZncJfvrtkyWnBEzO6E6NTqFB4ULg8dDssrSAi4+fKDabhiQALoaguerg+U9unfRz8pQU7/zZa/8oDrQPWqpq62okH+Ydud80gYO3iixQQYDtjoetQGYi70VFHmAq3MqiXDWl4EjkCLERmKYCHQhX8qILXV4ejubjf6xZk5iM5nr0/fhKG5ANVfdj94DhAYaZ0nVXuWjFGniEm/xtpXet29MIhmmyIIiK+mB/1yOKNSrwVxQjpuHek7XDFqZMQ4BXpvy3CPSUeYUFJ8115LXXY0XZ9w6XYpHoNEvFyQMgYE=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
conda_forge_output_validation: true
